# Generated by Django 5.2 on 2025-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submitted_Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('assignment_number', models.IntegerField()),
                ('path', models.FileField(upload_to='uploads/Submitted_Assignments')),
                ('semester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eight')])),
                ('section', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('submission_deadline', models.DateField()),
            ],
        ),
    ]
