# Generated by Django 5.2 on 2025-05-06 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DownloadUploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitted_assignments',
            name='submitted_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
