# Generated by Django 5.2 on 2025-05-05 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBuddy', '0005_roomparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', through='StudyBuddy.RoomParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
