# Generated by Django 3.1.12 on 2025-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='uploads/Notes')),
                ('sub_name', models.CharField(max_length=25)),
                ('semester', models.CharField(max_length=2)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
    ]
