# Generated by Django 3.1.12 on 2025-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0002_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Type',
            field=models.CharField(choices=[('Printed', 'Printed'), ('HandWritten', 'HandWritten')], max_length=25),
        ),
        migrations.AlterField(
            model_name='notes',
            name='semester',
            field=models.IntegerField(choices=[]),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='semester',
            field=models.IntegerField(choices=[]),
        ),
    ]
