# Generated by Django 3.1.12 on 2025-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0005_auto_20250129_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eight')]),
        ),
    ]
