# Generated by Django 3.1.12 on 2025-02-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0006_auto_20250129_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('assignment_number', models.IntegerField()),
                ('path', models.FileField(upload_to='uploads/Assignments')),
                ('semester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eight')])),
                ('department', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering')], max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('submission_deadline', models.DateField()),
            ],
        ),
    ]
