# Generated by Django 3.1.12 on 2025-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0007_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=50),
        ),
    ]
