# Generated by Django 3.1.12 on 2025-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0008_auto_20250203_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='sub_name',
            field=models.TextField(),
        ),
    ]
