# Generated by Django 5.2 on 2025-04-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUploads', '0009_auto_20250206_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
