# Generated by Django 5.2 on 2025-05-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('Print', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Seller_email', models.EmailField(max_length=254)),
                ('Seller_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
