# Generated by Django 3.1.12 on 2024-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='students',
    #         name='roll_number',
    #         field=models.BigIntegerField(unique=True),
    #     ),
    # ]
