# Generated by Django 3.1.12 on 2024-12-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
