# Generated by Django 3.1.12 on 2024-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20241218_0125'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='students',
    #         name='roll_number',
    #         field=models.CharField(max_length=50, unique=True),
    #     ),
    #]
