# Generated by Django 3.1.12 on 2024-12-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20241220_2204'),
        ('Home', '0004_auto_20241217_1857'),
    ]

    operations = [
    ]
