# Generated by Django 3.1.12 on 2024-12-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_merge_20241221_0129'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='students',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True),
        # ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100),
        ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='roll_number',
        #     field=models.CharField(max_length=50, unique=True),
        # ),
    ]
