# Generated by Django 3.1.12 on 2024-12-22 16:00
import datetime

utc = datetime.timezone.utc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0007_auto_20241221_0130"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='students',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='roll_number',
        #     field=models.CharField(max_length=50, unique=True),
        # ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        max_length=50,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 12, 22, 16, 0, 28, 179016, tzinfo=utc
                        )
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marked_attendance",
                        to="Home.faculties",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.sections"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.subjects"
                    ),
                ),
            ],
        ),
    ]
