# Generated by Django 3.1.12 on 2024-12-22 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20241222_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 19, 33, 34, 14088, tzinfo=utc)),
        ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='roll_number',
        #     field=models.CharField(max_length=50, unique=True),
        # ),
    ]
