# Generated by Django 3.1.12 on 2024-12-24 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20241225_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 19, 46, 3, 953297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='roll_number',
        #     field=models.CharField(max_length=50, unique=True),
        # ),
    ]
