# Generated by Django 3.1.12 on 2025-01-02 20:00

import datetime
utc = datetime.timezone.utc
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20241225_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 2, 20, 0, 0, 47196, tzinfo=utc)),
        ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='roll_number',
        #     field=models.CharField(max_length=50, unique=True),
        # ),
    ]
