# Generated by Django 3.1.12 on 2025-01-28 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20250126_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 16, 15, 18, 447606, tzinfo=utc)),
        ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='students',
        #     name='roll_number',
        #     field=models.CharField(max_length=50, unique=True),
        # ),
    ]
