# Generated by Django 3.1.12 on 2025-01-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20250130_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=200),
        ),
    ]
