# Generated by Django 3.1.12 on 2025-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20250201_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
