# Generated by Django 3.1.12 on 2025-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20250201_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
