# Generated by Django 5.2 on 2025-05-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_auto_20250201_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='year',
        ),
        migrations.AddField(
            model_name='students',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], max_length=100),
        ),
    ]
